spring:
    # Hibernate settings
    datasource:
        url: jdbc:h2:~/.h2/sa_airport
        platform: h2
        username: software
        password: architecture
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                show_sql: true
                use_sql_comments: true
                format_sql: true
        hibernate:
            # todo> configure the database persistence according to your needs
            # hint> if you use the provided docker script, then use docker_run.ps1 if ddl-auto is update
            # ddl-auto: create # use 'create' to get a clean database per application start
            ddl-auto: update # use 'update' to keep data between application starts
    # H2 Settings
    h2:
        console:
            enabled: true
            path: /h2
            settings:
                trace: false
                web-allow-others: true # must be enabled for docker
airport:
    runway-count: 4
